In [7]:
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import os

In [8]:
load_dotenv(override=True)

expert_file = os.getenv("EXPERT_FILE")
output_folder_path = os.getenv("OUTPUT_FOLDER_PATH")

In [9]:
df = pd.read_excel(expert_file, engine='openpyxl')
df

,N,Imagen,Ingredientes,Peso,kcal,P (g),CH (g),G (g),Observaciones
0,1.0,NaN,Malta,50.0,185.0,1.9,22.5,NaN,NaN
1,NaN,NaN,Agua,300.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Lúpulo,3.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Levadura,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
def clean_aggregate_data(df, output_path=output_folder_path,  filename_base="expert_cleaned"):
    df_clean = df.copy()
    df_clean['N'] = df_clean['N'].ffill()
    df_clean = df_clean.dropna(subset=['N'])

    result = df_clean.groupby('N').agg({
        'Ingredientes': lambda x: ', '.join(x.dropna().astype(str)),
        'kcal': 'sum',
        'P (g)': 'sum',
        'CH (g)': 'sum',
        'G (g)': 'sum',
        'Peso': 'sum',
        'Observaciones': lambda x: ', '.join(x.dropna().astype(str))
    })

    result['Ingredientes'] = result['Ingredientes'].replace('', np.nan)

    result = result.reset_index()

    result = result.rename(columns={
        'N': 'id',
        'Ingredientes': 'description',
        'kcal': 'calories',
        'P (g)': 'proteins',
        'CH (g)': 'carbohydrates',
        'G (g)': 'fats',
        'Peso': 'serving_size',
        'Observaciones': 'observaciones'
    })

    # Get current project directory
    current_dir = os.getcwd()

    # Define output file paths
    excel_path = os.path.join(output_path, f"{filename_base}.xlsx")
    json_path = os.path.join(current_dir, f"{filename_base}.json")

    # Export files
    result.to_excel(excel_path, index=False)
    result.to_json(json_path, orient='records', indent=2, force_ascii=False)

    print(f"Data exported to:\n- Excel: {excel_path}\n- JSON: {json_path}")
    return result

In [11]:
clean_aggregate_data(df)

Data exported to:
- Excel: /Users/martinhachiya/dev/datasets/nutria_backbone/llm_response/expert_cleaned.xlsx
- JSON: /Users/martinhachiya/dev/nutria_backbone/nutria_solution/expert/expert_cleaned.json

,id,description,calories,proteins,carbohydrates,fats,serving_size,observaciones
0,1.0,"Malta, Agua, Lúpulo, Levadura",185.00,1.900,22.50,0.000,353.0,
1,2.0,"Aceituna, Ajo, Pasta, Oregano, Aceite de oliva...",274.75,4.990,49.10,7.800,268.0,
2,3.0,"Tomate, Salmón, Huevo, Croasant",514.00,32.400,33.00,27.400,340.0,
3,4.0,"Papas fritas, Aceite de oliva, Carne de res, S...",547.00,24.300,65.00,31.000,223.0,
4,5.0,"Remolacha, Arroz, Carne de res",371.50,25.300,40.30,12.050,340.0,
5,6.0,"Brocoli, Lechuga, Carne de res, Tomate",206.75,21.675,4.55,11.425,205.0,
6,7.0,"Palta, Salmón",223.00,20.700,2.60,14.300,160.0,
7,8.0,"Café espresso, Agua",3.00,0.000,0.50,0.100,30.0,
8,9.0,"Café, Leche",58.00,3.950,6.40,1.800,150.0,
9,10.0,Agua,0.00,0.000,0.00,0.000,500.0,
10,11.0,Vino blanco,57.50,0.050,1.80,0.000,70.0,
11,12.0,Salame,340.00,19.000,0.60,28.500,90.0,
12,13.0,Plátano variedad seda,86.00,1.180,19.98,0.200,100.0,
13,14.0,NaN,0.00,0.000,0.00,0.000,0.0,
14,15.0,"Almendras, Maní variedad perla",370.70,13.700,12.98,29.320,60.0,Logro distinguir las almendras y el maní
15,16.0,"Agua, Canela, Azúcar granulada refinada",65.07,0.070,16.08,0.060,317.0,"Estoy en duda si es un te o un refresco, llegu..."
16,17.0,"Leche fresca fluida de vaca, Chocolate con lec...",242.00,8.120,32.76,8.630,140.0,Vaso pequeño de leche batida (con espuma)
17,18.0,"Huevo entero de gallina de granja, Tocino",491.50,15.030,11.44,42.810,150.0,
18,19.0,Chocolate en barra con azúcar,236.50,1.900,37.61,8.700,40.0,
19,20.0,Agua con hielo,0.00,0.000,0.00,0.000,400.0,
20,21.0,Agua natural,0.00,0.000,0.00,0.000,250.0,"Lo amarillo parece una esponja, no entendí muy..."
21,22.0,"Agua, Cocoa en polvo, Azúcar granulada refinada",127.20,3.070,23.43,2.350,260.0,
22,23.0,"Almendras, Maní variedad perla, Castaña, Cajú",682.40,20.500,18.30,58.560,130.0,"Ingredientes incompletos, no sé qué es el palito"
23,24.0,Vino tinto,76.00,0.200,0.00,0.000,100.0,Toda la información nutricional está basada en...
24,25.0,"Pollo pechuga, Zuccini, Zanahoria, Champiñones...",257.70,21.060,16.40,12.020,250.0,
25,26.0,Huevo entero de gallina de granja,132.00,13.520,2.49,7.500,100.0,
26,27.0,Manzana entera,125.80,0.470,0.20,0.340,170.0,
27,28.0,"Agua, Harina, Levadura, Aceite de oliva, Salsa...",2322.29,83.020,328.77,75.040,912.0,
28,29.0,Mandarina variedad owari satsuma,193.20,1.780,44.58,0.860,210.0,
29,30.0,"Fideo, Perejil",375.00,9.860,81.84,0.860,100.0,No estoy muy segura del perejil pero no se con...
30,31.0,"Agua, Levadura, Azúcar, Harina, Sal",3706.80,82.300,816.58,12.640,1670.0,Las medidas son en base a una marraqueta entera
31,32.0,"Pollo pierna, Pepino",211.00,21.070,7.53,10.740,200.0,Solo consigo distinguir el pepino y la otra gu...
32,33.0,"Fideo, Queso mozzarella, Tocino, Lechuga crespa",431.80,15.750,29.57,27.790,120.0,
33,34.0,NaN,0.00,0.000,0.00,0.000,0.0,
34,35.0,Queso cuartirolo,317.00,28.070,1.38,22.090,100.0,
35,36.0,"Plátano criollo, Huevo entero de gallina de gr...",1371.80,72.560,156.86,49.650,320.0,La composición del majadito está basada en el ...
36,37.0,"Charque (carne deshilachada), Huevo, Quesillo",3311.00,110.300,17.01,44.530,400.0,Se consigue ver en la imagen 3 unidades de hue...
37,38.0,NaN,0.00,0.000,0.00,0.000,0.0,
38,39.0,"Carne, Arroz, Huevo entero de gallina de granj...",662.30,41.480,55.19,31.560,355.0,
39,40.0,"Carne magra, Papa variedad alfa, Huevo entero ...",436.60,34.890,48.75,13.270,450.0,
40,41.0,Fricasé,363.00,19.860,51.06,8.670,300.0,Toda la composición nutricional está basada en...
41,42.0,"Charque, Huevo entero de gallina de granja, Pa...",1403.00,123.460,124.05,45.760,700.0,
42,43.0,NaN,0.00,0.000,0.00,0.000,0.0,
43,44.0,"Azúcar, Agua, Canela, Durazno variedad amarilla",427.02,0.300,106.26,0.110,432.0,
44,45.0,"Maní, Arroz, Papa, Agua",330.80,10.830,40.80,13.780,610.0,
45,46.0,NaN,0.00,0.000,0.00,0.000,0.0,
46,47.0,"Carne (lomo), Plátano criollo, Arroz, Ajo",407.96,27.920,66.47,3.370,222.0,
47,48.0,Arroz con leche,24.00,2.530,3.17,0.180,100.0,Toda la composición nutricional está basada en...
48,49.0,NaN,0.00,0.000,0.00,0.000,0.0,
49,50.0,NaN,0.00,0.000,0.00,0.000,0.0,